try to run this package from within posthog

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,6 +25,107 @@ jobs:
             - name: Lint with ESLint
               run: yarn lint
 
+    tests-starts-with-posthog:
+        name: Tests / Starts with PostHog
+        runs-on: ubuntu-20.04
+
+        services:
+            postgres:
+                image: postgres:12
+                env:
+                    POSTGRES_USER: postgres
+                    POSTGRES_PASSWORD: postgres
+                    POSTGRES_DB: test_posthog
+                ports: ['5432:5432']
+                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
+            redis:
+                image: redis
+                ports:
+                    - '6379:6379'
+                options: >-
+                    --health-cmd "redis-cli ping"
+                    --health-interval 10s
+                    --health-timeout 5s
+                    --health-retries 5
+
+        env:
+            REDIS_URL: 'redis://localhost'
+
+        steps:
+            - name: Check out Django server for database setup
+              uses: actions/checkout@v2
+              with:
+                  repository: 'PostHog/posthog'
+                  path: 'posthog/'
+
+            - name: Check out plugin server
+              uses: actions/checkout@v2
+              with:
+                  path: 'plugin-server'
+
+            - name: Set up Python
+              uses: actions/setup-python@v2
+              with:
+                  python-version: 3.8
+
+            - name: Set up Node 14
+              uses: actions/setup-node@v2
+              with:
+                  node-version: 14
+
+            - uses: actions/cache@v2
+              with:
+                  path: ${{ env.pythonLocation }}
+                  key: ${{ env.pythonLocation }}-v1-${{ hashFiles('posthog/requirements.txt') }}
+
+            - name: Install requirements.txt dependencies with pip
+              run: |
+                  pip install --upgrade pip
+                  pip install --upgrade --upgrade-strategy eager -r posthog/requirements.txt
+
+            - name: Set up databases
+              env:
+                  SECRET_KEY: 'abcdef' # unsafe - for testing only
+                  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/posthog'
+                  TEST: 'true'
+              run: python posthog/manage.py setup_test_environment
+
+            - name: Build the plugin server and link it with yarn
+              run: |
+                  cd plugin-server
+                  yarn
+                  yarn build
+                  yarn link
+
+            - name: Run the linked plugin server from under `posthog/plugins`
+              timeout-minutes: 2
+              run: |
+                  cd posthog/plugins
+                  yarn link "@posthog/plugin-server"
+                  yarn
+
+                  # start this in the background
+                  yarn start &> tmplog.txt &
+                  pid=$!
+
+                  sleep 10
+
+                  # check if it's still running, as it should be
+                  if ! kill $pid > /dev/null 2>&1; then
+                      echo "Could not send SIGTERM to process $pid" >&2
+                      exit 1
+                  fi
+
+                  str=`cat tmplog.txt | grep "All systems go"`
+                  if [ ! "$str" ];then
+                      echo 'Did not find "All systems go" in plugin server log output!'
+                      echo ""
+                      cat tmplog.txt
+                      exit 1
+                  fi
+
+                  rm tmplog.txt
+
     tests-postgres-1:
         name: Tests / Postgres + Redis (1)
         runs-on: ubuntu-20.04
